<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CultureFitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = now();

        $list = [
            [
                'id'          => 1,
                'name'        => 'Accountability',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 2,
                'name'        => 'Aesthetics',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 3,
                'name'        => 'Agility',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 4,
                'name'        => 'Balance',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 5,
                'name'        => 'Belonging',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 6,
                'name'        => 'Charity',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 7,
                'name'        => 'Collaboration',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 8,
                'name'        => 'Commitment (F)',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 9,
                'name'        => 'Communication',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 10,
                'name'        => 'Community',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 11,
                'name'        => 'Continuous-Learning',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 12,
                'name'        => 'Creativity',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 13,
                'name'        => 'Customer-Obsession',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 14,
                'name'        => 'Discipline',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 15,
                'name'        => 'Diversity',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 16,
                'name'        => 'Efficiency',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 17,
                'name'        => 'Entrepreneurship',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 18,
                'name'        => 'Ethics',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 19,
                'name'        => 'Excellence',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 20,
                'name'        => 'Factualness (M)',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 20,
                'name'        => 'Fairness',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 21,
                'name'        => 'Fast-Learning',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 22,
                'name'        => 'Global',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 23,
                'name'        => 'Family',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 24,
                'name'        => 'Fun',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 25,
                'name'        => 'Growth (M)',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 26,
                'name'        => 'Hard Work',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 27,
                'name'        => 'Honesty (F)',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 28,
                'name'        => 'Hospitality',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 29,
                'name'        => 'Humility',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 30,
                'name'        => 'Idealism',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 31,
                'name'        => 'Impact',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 32,
                'name'        => 'Inclusion',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 33,
                'name'        => 'Innovation',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 34,
                'name'        => 'Integrity',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 35,
                'name'        => 'Kindness (F)',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 36,
                'name'        => 'Leadership (M)',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 37,
                'name'        => 'Mindfulness',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 38,
                'name'        => 'Pleasure',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 39,
                'name'        => 'Professionalism',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 40,
                'name'        => 'Safety',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 41,
                'name'        => 'Security',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 42,
                'name'        => 'Service',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 43,
                'name'        => 'Simplicity',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 44,
                'name'        => 'Sustainability',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 45,
                'name'        => 'Tradition',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 46,
                'name'        => 'Transparency',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 47,
                'name'        => 'Trust (F)',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 48,
                'name'        => 'Wellbeing',
                'category_id' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            
            [
                'id'          => 49,
                'name'        => 'Adaptable',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 50,
                'name'        => 'Altruistic',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 51,
                'name'        => 'Ambitious (M)',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 52,
                'name'        => 'Analytic (M)',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 53,
                'name'        => 'Approachable',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 54,
                'name'        => 'Careful',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 55,
                'name'        => 'Caring (F)',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 56,
                'name'        => 'Communicating',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 57,
                'name'        => 'Confident (M)',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 59,
                'name'        => 'Courageous (M)',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 60,
                'name'        => 'Critical-Thinking',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 61,
                'name'        => 'Culturally-Intelligent',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 62,
                'name'        => 'Curious',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 63,
                'name'        => 'Decision-Making',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 64,
                'name'        => 'Delegating',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 65,
                'name'        => 'Dependable',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 66,
                'name'        => 'Diplomatic',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 67,
                'name'        => 'Elegant (F)',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 68,
                'name'        => 'Eloquent',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 69,
                'name'        => 'Empathetic',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 70,
                'name'        => 'Energetic',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 71,
                'name'        => 'Entrepreneurial',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 72,
                'name'        => 'Extroverted',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 73,
                'name'        => 'Fast-Learning',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 74,
                'name'        => 'Flexible',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 75,
                'name'        => 'Focused',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 76,
                'name'        => 'Friendly',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 77,
                'name'        => 'Honest',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 78,
                'name'        => 'Influential',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 79,
                'name'        => 'Introverted',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 80,
                'name'        => 'Listening',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 81,
                'name'        => 'Negotiating',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 82,
                'name'        => 'Observing',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 83,
                'name'        => 'Open-minded',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 84,
                'name'        => 'Passionate',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 85,
                'name'        => 'Proactive (M)',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 86,
                'name'        => 'Problem-Solving',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 87,
                'name'        => 'Proficient',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 88,
                'name'        => 'Punctual',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 89,
                'name'        => 'Relationship-Building',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 90,
                'name'        => 'Resilient',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 100,
                'name'        => 'Responsible (F)',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 101,
                'name'        => 'Result-Oriented',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 102,
                'name'        => 'Self-Aware',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 103,
                'name'        => 'Supportive (F)',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 104,
                'name'        => 'Strict',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 105,
                'name'        => 'Team Building',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 106,
                'name'        => 'Teamworking',
                'category_id' => 2,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            [
                'id'          => 107,
                'name'        => 'Analyze Complex Data and come up with Simple Conclusions',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 108,
                'name'        => 'Career Advancement',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 109,
                'name'        => 'Challenge the Status Quo',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 110,
                'name'        => 'Empower Others',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 111,
                'name'        => 'Find Innovative Solutions',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 112,
                'name'        => 'Flexibility',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 113,
                'name'        => 'Fun',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 114,
                'name'        => 'Give Back',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 115,
                'name'        => 'Good Pay',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 117,
                'name'        => 'Great Colleagues',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 118,
                'name'        => 'Great Work Environment',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 119,
                'name'        => 'Lead a Team to Success',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 120,
                'name'        => 'Learn Something New',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 121,
                'name'        => 'Make an Impact',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 122,
                'name'        => 'Personal Development',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 123,
                'name'        => 'Progress',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 124,
                'name'        => 'Prove Some People Wrong',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 125,
                'name'        => 'Recognition and Respect',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 126,
                'name'        => 'Satisfy Curiosity',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 128,
                'name'        => 'Self-Actualization',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 129,
                'name'        => 'Sense of Belonging',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 130,
                'name'        => 'Share Knowledge and Help Others Succeed',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 131,
                'name'        => 'Solve Challenges',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'id'          => 132,
                'name'        => 'Spot Flaws and Fix Them',
                'category_id' => 3,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
        ];

        foreach ($list as $item) {
            DB::table('culture_fits')->updateOrInsert([ 'id' => $item['id'] ], $item);
        }
    }
}
