<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     *
     * @return void
     */
    public function run()
    {
        $now = now();

        $languages = [
            [
              'id'         => 'AB',
              'name'       => 'Abkhazian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'AA',
              'name'       => 'Afar',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'AF',
              'name'       => 'Afrikaans',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SQ',
              'name'       => 'Albanian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'AM',
              'name'       => 'Amharic',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'AR',
              'name'       => 'Arabic',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'HY',
              'name'       => 'Armenian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'AS',
              'name'       => 'Assamese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'AY',
              'name'       => 'Aymara',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'AZ',
              'name'       => 'Azerbaijani',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'BA',
              'name'       => 'Bashkir',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'EU',
              'name'       => 'Basque',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'BN',
              'name'       => 'Bengali',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'DZ',
              'name'       => 'Bhutani',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'BH',
              'name'       => 'Bihari',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'BI',
              'name'       => 'Bislama',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'BR',
              'name'       => 'Breton',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'BG',
              'name'       => 'Bulgarian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'MY',
              'name'       => 'Burmese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'BE',
              'name'       => 'Byelorussian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'KM',
              'name'       => 'Cambodian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'CA',
              'name'       => 'Catalan',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'ZH',
              'name'       => 'Chinese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'CO',
              'name'       => 'Corsican',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'HR',
              'name'       => 'Croatian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'CS',
              'name'       => 'Czech',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'DA',
              'name'       => 'Danish',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'NL',
              'name'       => 'Dutch',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'EN',
              'name'       => 'English',
              'enabled'    => true,
              'is_default' => true,
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'EO',
              'name'       => 'Esperanto',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'ET',
              'name'       => 'Estonian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'FO',
              'name'       => 'Faeroese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'FJ',
              'name'       => 'Fiji',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'FI',
              'name'       => 'Finnish',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'FR',
              'name'       => 'French',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'FY',
              'name'       => 'Frisian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'GD',
              'name'       => 'Gaelic (Scots Gaelic)',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'GL',
              'name'       => 'Galician',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'KA',
              'name'       => 'Georgian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'DE',
              'name'       => 'German',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'EL',
              'name'       => 'Greek',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'KL',
              'name'       => 'Greenlandic',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'GN',
              'name'       => 'Guarani',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'GU',
              'name'       => 'Gujarati',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'HA',
              'name'       => 'Hausa',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'IW',
              'name'       => 'Hebrew',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'HI',
              'name'       => 'Hindi',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'HU',
              'name'       => 'Hungarian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'IS',
              'name'       => 'Icelandic',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'IN',
              'name'       => 'Indonesian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'IA',
              'name'       => 'Interlingua',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'IE',
              'name'       => 'Interlingue',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'IK',
              'name'       => 'Inupiak',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'GA',
              'name'       => 'Irish',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'IT',
              'name'       => 'Italian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'JA',
              'name'       => 'Japanese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'JW',
              'name'       => 'Javanese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'KN',
              'name'       => 'Kannada',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'KS',
              'name'       => 'Kashmiri',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'KK',
              'name'       => 'Kazakh',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'RW',
              'name'       => 'Kinyarwanda',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'KY',
              'name'       => 'Kirghiz',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'RN',
              'name'       => 'Kirundi',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'KO',
              'name'       => 'Korean',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'KU',
              'name'       => 'Kurdish',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'LO',
              'name'       => 'Laothian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'LA',
              'name'       => 'Latin',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'LV',
              'name'       => 'Latvian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'LN',
              'name'       => 'Lingala',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'LT',
              'name'       => 'Lithuanian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'MK',
              'name'       => 'Macedonian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'MG',
              'name'       => 'Malagasy',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'MS',
              'name'       => 'Malay',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'ML',
              'name'       => 'Malayalam',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'MT',
              'name'       => 'Maltese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'MI',
              'name'       => 'Maori',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'MR',
              'name'       => 'Marathi',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'MO',
              'name'       => 'Moldavian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'MN',
              'name'       => 'Mongolian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'NA',
              'name'       => 'Nauru',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'NE',
              'name'       => 'Nepali',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'NO',
              'name'       => 'Norwegian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'OC',
              'name'       => 'Occitan',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'OR',
              'name'       => 'Oriya',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'OM',
              'name'       => 'Oromo',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'PS',
              'name'       => 'Pashto',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'FA',
              'name'       => 'Persian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'PL',
              'name'       => 'Polish',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'PT',
              'name'       => 'Portuguese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'PA',
              'name'       => 'Punjabi',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'QU',
              'name'       => 'Quechua',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'RM',
              'name'       => 'Rhaeto-Romance',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'RO',
              'name'       => 'Romanian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'RU',
              'name'       => 'Russian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SM',
              'name'       => 'Samoan',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SG',
              'name'       => 'Sangro',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SA',
              'name'       => 'Sanskrit',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SR',
              'name'       => 'Serbian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SH',
              'name'       => 'Serbo-Croatian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'ST',
              'name'       => 'Sesotho',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TN',
              'name'       => 'Setswana',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SN',
              'name'       => 'Shona',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SD',
              'name'       => 'Sindhi',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SI',
              'name'       => 'Singhalese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SS',
              'name'       => 'Siswati',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SK',
              'name'       => 'Slovak',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SL',
              'name'       => 'Slovenian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SO',
              'name'       => 'Somali',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'ES',
              'name'       => 'Spanish',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SU',
              'name'       => 'Sudanese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SW',
              'name'       => 'Swahili',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'SV',
              'name'       => 'Swedish',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TL',
              'name'       => 'Tagalog',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TG',
              'name'       => 'Tajik',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TA',
              'name'       => 'Tamil',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TT',
              'name'       => 'Tatar',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TE',
              'name'       => 'Tegulu',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TH',
              'name'       => 'Thai',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'BO',
              'name'       => 'Tibetan',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TI',
              'name'       => 'Tigrinya',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TO',
              'name'       => 'Tonga',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TS',
              'name'       => 'Tsonga',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TR',
              'name'       => 'Turkish',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TK',
              'name'       => 'Turkmen',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'TW',
              'name'       => 'Twi',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'UK',
              'name'       => 'Ukrainian',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'UR',
              'name'       => 'Urdu',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'UZ',
              'name'       => 'Uzbek',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'VI',
              'name'       => 'Vietnamese',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'VO',
              'name'       => 'Volapuk',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'CY',
              'name'       => 'Welsh',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'WO',
              'name'       => 'Wolof',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'XH',
              'name'       => 'Xhosa',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'JI',
              'name'       => 'Yiddish',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
              'id'         => 'YO',
              'name'       => 'Yoruba',
              'created_at' => $now,
              'updated_at' => $now,
            ],
            [
                'id'         => 'ZU',
                'name'       => 'Zulu',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        foreach ($languages as $language) {
            DB::table('languages')->updateOrInsert( [ 'id' => $language['id'] ], $language);
        }
    }
}
